---

- name: Run cleanup
  hosts: scylla
  gather_facts: false
  serial: "{{ batch_size |default(1) }}"
  vars:
    cleanup_async: 2592000
    cleanup_retries: 43200
    cleanup_delay: 60
  tasks:
    - name: Check if '--limit' argument was used
      fail:
        msg: "You must use -l or --limit. To cleanup the entire cluster, use -l 'all'"
      when: ansible_limit is not defined

    - name: Run cleanup (no DC and rack aware)
      ansible.builtin.import_tasks: cleanup.yaml
      when:
        - cleanup_dc is not defined
        - cleanup_rack is not defined

    - name: Run cleanup (DC and rack aware)
      ansible.builtin.import_tasks: cleanup.yaml
      when:
        - cleanup_dc is defined
        - cleanup_rack is defined
        - cleanup_dc == dc
        - cleanup_rack == rack
