---
- name: Update apt cache
  apt:
    update_cache: yes
  become: true

- name: docker prepwork
  block:
  - name: Uninstall old versions
    apt:
      name:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc
      state: absent

  - name: install dependencies
    apt:
      name:
        - python3
        - python3-yaml
        - git
        - wget
        - apt-transport-https
        - software-properties-common
        - adduser
        - libfontconfig1
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
      state: present

  - name: add docker's apt key
    apt_key:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present

  - name: add repo
    shell: |
      sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"

  - name: Update apt cache
    apt:
      update_cache: yes

  - name: install docker
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
  become: true
  when: install_type == "docker"
