---
- name: Change owner and group for 'data' directory
  ansible.builtin.file:
    path: "{{ scylla_monitoring_prometheus_data_path }}"
    state: directory
    mode: '1755'
    recurse: yes
    owner: "nobody"
    group: "nogroup"
  become: true
  when: run_docker_with_sudo is defined and run_docker_with_sudo|bool == True

- name: create docker group
  group:
    name: docker
    state: present
  become: true

- name: "Get all groups '{{ ansible_user_id }}' has its membership to 'docker' group active"
  ansible.builtin.shell: id
  register: user_info

- name: add user to the docker group
  user:
    name: '{{ ansible_user_id }}'
    groups: docker
    append: yes
  become: true

- name: "Reboot if '{{ ansible_user_id }}' membership to 'docker' group it not active"
  ansible.builtin.reboot:
    msg: "Rebooted by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: id
  when: "not '(docker)' in user_info.stdout"
  become: true

- name: enable docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: true

- set_fact:
    monitoring_cql_username: "{{ item.split('=')[0] }}"
    monitoring_cql_password: "{{ item.split('=')[1] }}"
  when: "'cql_credentials' in groups and item.split('=')[0] == scylla_monitoring_cql_default_user | default('scylla_cql_monitor')"
  loop: "{{ groups['cql_credentials'] }}"

- name: "Copy 'start_scylla_monitoring_{{ scylla_monitoring_version | replace('.', '_') }}.sh'"
  ansible.builtin.template:
    src: templates/start_scylla_monitoring.j2
    dest: "{{ scylla_monitoring_installation_path }}/start_scylla_monitoring_{{ scylla_monitoring_version | replace('.', '_') }}.sh"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0755'
  register: start_scylla_monitoring_script
  become: true

- name: Start Scylla Monitoring stack
  ansible.builtin.shell: "{{ start_scylla_monitoring_script.dest }}"
  environment:
    SCYLLA_USER: "{% if monitoring_cql_username is defined and monitoring_cql_password is defined %}{{ monitoring_cql_username }}{% endif %}"
    SCYLLA_PSSWD: "{% if monitoring_cql_username is defined and monitoring_cql_password is defined %}{{ monitoring_cql_password }}{% endif %}"
  become: "{{ run_docker_with_sudo | bool | default(False) }}"
