---
- name: Check for any existing legacy installation/configuration
  ansible.builtin.include_tasks: legacy.yml

- name: os-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: common tasks
  ansible.builtin.include_taskss: common.yml

- name: install dockerized monitoring
  ansible.builtin.include_tasks: docker.yml
  when: install_type == 'docker'

- name: install non-dockerized monitoring
  ansible.builtin.include_tasks: non-docker.yml
  when: install_type != 'docker'

- name: Post-installation cleanup
  ansible.builtin.include_tasks: post_cleanup.yml
